version: '3.6'

volumes:
  postgres-data: 

services:
  api:
    build:
      context: .
    container_name: clean-arch_api
    ports:
      - "5000:5000"
      - "5001:5001"

  postgres:
    image: postgres:10.5-alpine
    container_name: clean-arch_postgres
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - postgres-data:/var/lib/postgresql/data
    - ./resources/backups:/var/backups